version: '3.8'

services:
  db:
    image: mariadb:10.5
    container_name: local-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: localdb
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mariadb/data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    name: local_app_network
    driver: bridge
    external: false